//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.RideForUsers = new HashSet<RideForUser>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime TripDate { get; set; }
        public int MembersNum { get; set; }
        public int MinAge { get; set; }
        public int MaxAge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideForUser> RideForUsers { get; set; }
        public virtual User User { get; set; }
    }
}
